### ISSUE TITLE
problem when run FV model

### ISSUE THREAD

**Issue by wjczf123** [ShannonAI/OpenViDial#28]
2021-03-20 12:27:30 | INFO | fairseq.utils | ***********************CUDA enviroments for all 4 workers***********************
2021-03-20 12:27:30 | INFO | fairseq_cli.train | training on 4 devices (GPUs/TPUs)
2021-03-20 12:27:30 | INFO | fairseq_cli.train | max tokens per GPU = 8000 and max sentences per GPU = 32
2021-03-20 12:27:30 | INFO | fairseq.trainer | no existing checkpoint found train_logs/reproduce_img_object/layer3_lr2e-4_bsz128_drop0.3_warmup6000/checkpoint_last.pt
2021-03-20 12:27:30 | INFO | fairseq.trainer | loading train data for epoch 1
2021-03-20 12:27:30 | INFO | video_dialogue_model.data.object_dataset | find minimum truncate of preprocessed_data_dir-train: 0
2021-03-20 12:38:39 | INFO | fairseq.data.data_utils | loaded 974803 examples from: preprocessed_data_dir/train
2021-03-20 12:39:10 | INFO | fairseq.trainer | NOTE: your device may support faster training with --fp16
epoch 001:   0%|                                                                                  | 0/7045 [00:00<?, ?it/s]2021-03-20 12:39:10 | INFO | fairseq.trainer | begin training epoch 1
Traceback (most recent call last):
  File "/usr/local/bin/fairseq-train", line 8, in <module>
    sys.exit(cli_main())
  File "/usr/local/lib/python3.6/dist-packages/fairseq_cli/train.py", line 352, in cli_main
    distributed_utils.call_main(args, main)
  File "/usr/local/lib/python3.6/dist-packages/fairseq/distributed_utils.py", line 286, in call_main
    nprocs=args.distributed_num_procs,
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 108, in join
    (error_index, name)
Exception: process 1 terminated with signal SIGKILL

This seems to be a problem caused by insufficient memory. The memory of my computer is 200G.
How much memory does the FV model need? Or is it caused by other reasons?

**Comment by YuxianMeng** [comment]
@wjczf123 We run the model with a machine with 300G memory.

**Comment by wjczf123** [comment]
Thank you a lot. Is there any way to solve this problem?


------------------ Original ------------------
From: Yuxian Meng ***@***.***&gt;
Date: 周一,3月 22,2021 09:49
To: ShannonAI/OpenViDial ***@***.***&gt;
Cc: wjczf123 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [ShannonAI/OpenViDial] problem when run FV model (#28)





 
@wjczf123 We run the model with a machine with 300G memory.

**Comment by YuxianMeng** [comment]
@wjczf123 I'll take a look this week, but solving this problem may take some time. If you'd like to run it now, maybe you can try using a smaller `--num-workers`

**Comment by wjczf123** [comment]
Ok. Thank you very much!&nbsp;


------------------ Original ------------------
From: Yuxian Meng ***@***.***&gt;
Date: 周一,3月 22,2021 11:59
To: ShannonAI/OpenViDial ***@***.***&gt;
Cc: wjczf123 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [ShannonAI/OpenViDial] problem when run FV model (#28)





 
@wjczf123 I'll take a look this week, but solving this problem may take some time. If you'd like to run it now, maybe you can try using a smaller --num-workers
